const antibioticos = [
"ácido clavulânico",
"ácido fusídico",
"ácido nalidíxico",
"ácido oxolínico",
"ácido pipemídico",
"amicacina",
"amoxicilina",
"ampicilina",
"axetilcefuroxima",
"azitromicina",
"aztreonam",
"bacitracina",
"besifloxacino",
"brodimoprima",
"capreomicina",
"carbenicilina",
"cefaclor",
"cefadroxil",
"cefalexina",
"cefalotina",
"cefazolina",
"cefepima",
"cefodizima",
"cefoperazona",
"cefotaxima",
"cefoxitina",
"cefpodoxima",
"cefepiroma",
"cefprozil",
"ceftazidima",
"ceftarolina fosamila",
"ceftobiprol",
"ceftriaxona",
"cefuroxima",
"ciprofloxacina",
"claritromicina",
"clindamicina",
"clofazimina",
"clorfenesina",
"cloranfenicol",
"cloxacilina",
"daptomicina",
"dapsona",
"dicloxacilina",
"diritromicina",
"doripenem",
"doxiciclina",
"eritromicina",
"ertapenem",
"espectinomicina",
"espiramicina",
"estreptomicina",
"etambutol",
"etionamida",
"fosfomicina",
"gatifloxacina",
"gentamicina",
"imipenem",
"isoniazida",
"levofloxacina",
"linezolida",
"lincomicina",
"lomefloxacina",
"meropenem",
"metronidazol",
"minociclina",
"moxifloxacino",
"mupirocina",
"neomicina",
"nitrofurantoína",
"norfloxacina",
"ofloxacina",
"oxacilina",
"oxitetraciclina",
"penicilina g",
"penicilina v",
"piperacilina",
"pirazinamida",
"polimixina b",
"pristinamicina",
"protionamida",
"retapamulina",
"rifampicina",
"rifabutina",
"rifapentina",
"roxitromicina",
"sulfametoxazol",
"tazobactam",
"teicoplanina",
"telitromicina",
"tetraciclina",
"ticarcilina",
"tigeciclina",
"tobramicina",
"trimetoprima",
"vancomicina"
];
